=== Joknaa/XML-CV/.other/cv.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT cv (entete,Formations,stages,competences,langues,loisirs)>
<!ATTLIST  cv  code  CDATA #REQUIRED >
<!ELEMENT entete (nom,prenom,dateDeNaisssance,nationalite,telephone,mail)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT dateDeNaisssance (#PCDATA)>
<!ELEMENT nationalite (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT Formations (diplome+)>
<!ELEMENT diplome (annee,intitule)>
<!ELEMENT annee (#PCDATA)>
<!ELEMENT intitule (#PCDATA)>
<!ELEMENT stages (stage+)>
<!ELEMENT stage (date,titre,description)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT competences (competence+)>
<!ELEMENT competence ((titre_competence)+,(description_competence)?)>
<!ELEMENT titre_competence (#PCDATA)>
<!ELEMENT description_competence (#PCDATA)>
<!ELEMENT langues (langue+)>
<!ELEMENT langue (intitule_langue, niveau)>
<!ELEMENT intitule_langue (#PCDATA)>
<!ELEMENT niveau (#PCDATA)>
<!ELEMENT loisirs (loisir+)>
<!ELEMENT loisir (#PCDATA)>

=== Joknaa/XML-CV/.other/Mon_CV.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "cv.dtd">
<?xml-stylesheet type="text/xsl" href="Mon_CV.XSL"?>
<cv code="utc.fr/nf29/crozatst/schema/cv">
    <entete>
        <nom>Laadidaoui</nom>
        <prenom>Mohammad</prenom>
        <dateDeNaisssance>25/06/1998</dateDeNaisssance>
        <nationalite>Marocain</nationalite>
        <telephone>+212 708008065</telephone>
        <mail>MohammadLaadidaoui@gmail.com</mail>
    </entete>
    <Formations>
        <diplome>
            <annee>2022</annee>
            <intitule>Diplôme d'ingénieur d'état: Génie Informatique</intitule>
        </diplome>
        <diplome>
            <annee>2016</annee>
            <intitule>Baccalauréat: option scientifique</intitule>
        </diplome>
    </Formations>
    <stages>
        <stage>
            <date>--2019--</date>
            <titre>Stage d'initiation:</titre>
            <description>Développement d'un site web pour la gestion des achates</description>
        </stage>
    </stages>


    <competences>
        <competence>
            <titre_competence>Java</titre_competence>
        </competence>
        <competence>
            <titre_competence>PHP/JS/HTML/CSS</titre_competence>
            <description_competence>: Programmation Web</description_competence>
        </competence>
    </competences>
    <langues>
        <langue>
            <intitule_langue>Arabe:</intitule_langue>
            <niveau>Maternelle</niveau>
        </langue>
        <langue>
            <intitule_langue>Anglais:</intitule_langue>
            <niveau>B2</niveau>
        </langue>
        <langue>
            <intitule_langue>Français:</intitule_langue>
            <niveau>C1</niveau>
        </langue>
    </langues>
    <loisirs>
        <loisir>Voyage</loisir>
        <loisir>Cuisine</loisir>
        <loisir>Lecture: développement personnel</loisir>
    </loisirs>
</cv>
